### ISSUE TITLE
Error while installing runtime, needs `sudo` from CLI.

### ISSUE THREAD

**Issue by ThatOneCalculator** [filips123/FirefoxPWA#10]
OS: Artix GNU/Linux
![image](https://user-images.githubusercontent.com/44733677/124372518-45617f80-dc3f-11eb-866f-f6846f8dfc30.png)
I have 7zip installed via `yay -S 7zip-bin`

**Comment by ThatOneCalculator** [comment]
CLI shows: 
```
~   firefoxpwa runtime install
03:46:40 [WARN] This will download the unmodified Mozilla Firefox and locally modify it
03:46:40 [WARN] Firefox is licensed under the Mozilla Public License 2.0
03:46:40 [WARN] Firefox is a trademark of the Mozilla Foundation in the U.S. and other countries
03:46:40 [WARN] This project is not affiliated with the Mozilla Foundation in any way
03:46:40 [WARN] By using this project you also agree to the Firefox Privacy Notice: https://www.mozilla.org/privacy/firefox/
03:46:40 [WARN] Check the Firefox website for more details: https://www.mozilla.org/firefox/
03:46:40 [INFO] Downloading the runtime archive
03:46:50 [INFO] Extracting the runtime archive
03:46:56 [INFO] Copying the runtime
03:46:56 [ERROR] Failed to install runtime

Caused by:
    0: Failed to copy the runtime
    1: Permission denied (os error 13)
```

Running with `sudo` works.

**Comment by filips123** [comment]
I forgot to add to the install steps that you need to make `/usr/share/firefoxpwa/runtime/` writable by normal users before installing the runtime. This is needed so FirefoxPWA can install the runtime and for Firefox auto-updates to work. However, if you do not plan to use Firefox auto-updates, you can also restore the permissions after the runtime is installed.

I will add this to install steps in the next release.

**Comment by filips123** [comment]
I updated install steps in the latest release (0.3.0).
