### ISSUE TITLE
Tabbing Option for PWAs 

### ISSUE THREAD

**Issue by pc-v2** [filips123/FirefoxPWA#12]
Using PWAs like usual browser but restricted to only PWAs website without address bar

**Comment by pc-v2** [comment]
example of usage

> open other site link in newtab

![image](https://user-images.githubusercontent.com/58063311/124384568-1bba5e00-dcfc-11eb-98d6-d43038e6bab0.png)

**Comment by filips123** [comment]
I implemented an option to enable tabs mode. It will be available in the next release.

It's disabled by default but can be enabled from `about:config` (`firefoxpwa.enableTabsMode`) or from Firefox settings ("Show browser tabs and enable using multiple tabs of the same app"). After tabs mode is enabled, you will need to restart the PWA browser, then it will display tabs, similarly to the normal browser, but without URL bar. Also, new tab page is replaced by a PWA start URL.


https://user-images.githubusercontent.com/16626308/124516184-66fa6c80-dde1-11eb-9891-6bde4551c035.mp4
