### ISSUE TITLE
teams.microsoft.com isn't installable

### ISSUE THREAD

**Issue by peterbev** [filips123/FirefoxPWA#14]
You can install the Teams PWA in both Edge and Chrome, but the option to install isn't available for FirefoxPWA

**Comment by filips123** [comment]
Microsoft Teams is not actually a real valid PWA (it doesn't have any manifest). However, Edge and Chrome also support installing non-PWA sites so it can still be installed.

FirefoxPWA currently doesn't support that but I will add support in the future. This will be tracked in #15.
