### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by ThatOneCalculator** [filips123/FirefoxPWA#20]
```
Create an empty directory /usr/share/firefoxpwa/runtime/ and make it writable by normal users. This is needed for FirefoxPWA runtime installation and Firefox auto-updates to work. If you do not plan to use Firefox auto-updates, you can restore the permissions after the runtime is installed. 
```

This doesn't tell the user *how* to make it writable. I'd assume `chmod 744`, but not everyone knows that.

**Comment by filips123** [comment]
Because `sudo mkdir -p /usr/share/firefoxpwa/runtime/` creates directory owned by `root`, it actually needs to be `sudo chmod 777` or the owner needs to be changed to a normal user (`sudo chown user /usr/share/firefoxpwa/runtime/`).

I will update the installation instructions with that info.

**Comment by ThatOneCalculator** [comment]
Yea, so you should add that to the instructions. Also maybe just place a command list with like `sudo cp` all the bin files, or just better yet make a post-install script.

**Comment by filips123** [comment]
I've added a list of commands to README and linked it from the extension install page. The list includes everything that is needed for installation, except Rust and Git installation because this very likely depends on OS and distro.
