### ISSUE TITLE
Twitter Shows White Background While Scrolling When Enabling Dark Mode

### ISSUE THREAD

**Issue by pc-v2** [filips123/FirefoxPWA#22]
![image](https://user-images.githubusercontent.com/58063311/124594787-6cf85800-de8a-11eb-8bf6-3dd59692e683.png)
![image](https://user-images.githubusercontent.com/58063311/124596177-2c99d980-de8c-11eb-8730-312efe7ddaf5.png)

**Comment by filips123** [comment]
I will fix this later, but the current workaround is to disable `firefoxpwa.sitesSetBackgroundColor` in `about:config`.
