### ISSUE TITLE
Cross origin error at install

### ISSUE THREAD

**Issue by black7375** [filips123/FirefoxPWA#23]
**Install target:** https://www.tumblr.com/

**Error Message**
```
Failed to parse PWA manifest: Provided URLs (https://assets.tumblr.com/dashboard?installed=true, https://www.tumblr.com/) are not in the same origin
```

**Comment by filips123** [comment]
Tumblr's web app manifest does not comply with [the official specification](https://w3c.github.io/manifest/#start_url-member):

> Let start URL be the result of parsing json["start_url"], using **manifest URL** as the base URL.
> If start URL is not same origin as **document URL**, return.

This is something that Tumblr developers need to fix. However, in the next release of FirefoxPWA, you will be able to uncheck "Use the manifest for determining app properties" when installing the site which will probably fix the issue.
