### ISSUE TITLE
Support installing runtime into `~/.local/share`

### ISSUE THREAD

**Issue by PeterCxy** [filips123/FirefoxPWA#24]
It would be nice if a world-writable `/usr/share/firefoxpwa/runtime` is not a hard requirement for using this extension. It may (for example) fall back onto downloading and installing the runtime into the user-accessible directory `~/.local/share` instead.

**Comment by filips123** [comment]
Currently you can only modify runtime directory by changing the source code. If you want to change just runtime directory, you need to change [this line](https://github.com/filips123/FirefoxPWA/blob/8d8adb87ddbc078a56d17ba08fd46f90acf0215e/native/src/components/runtime.rs#L70), if you want to check all installation directories, check [this comment](https://github.com/filips123/FirefoxPWA/issues/17#issuecomment-874002171) for instructions.

I will probably allow configuring this (either with some compile-time or run-time option) in the future, along with other requests abot configuring installation directories and properies (#6, #17, #24).

**Comment by PeterCxy** [comment]
Thanks. For now I've patched the code in my AUR package to move the runtime installation directory to `~/.local/share/firefoxpwa/runtime`. Package managers generally like it better when the packaged program do not write to `/usr` (except `/usr/local`) directly, so supporting this as an option would make packaging it cleanly a bit easier. (However, adding a compilation option for this would require the ability to parse the `~` syntax and replace it with the HOME env variable depending on the path string provided as the option, which may require using `build.rs`).

**Comment by filips123** [comment]
Starting with https://github.com/filips123/FirefoxPWA/commit/df05306fae01916834575d9d6bd5e371a68ee919, runtime will be installed into user directory by default.

If anyone wants to change it back or use other locations, I added [few comments](https://github.com/filips123/FirefoxPWA/blob/df05306fae01916834575d9d6bd5e371a68ee919/native/src/components/runtime.rs#L70-L72) in the code. It is still required to change the source code as using build-time env vars would complicate things, but I might change this in the future.
