### ISSUE TITLE
Version 0.3.1 profile doesn't have new tab button in 0.4.0

### ISSUE THREAD

**Issue by pc-v2** [filips123/FirefoxPWA#28]
![image](https://user-images.githubusercontent.com/58063311/124921985-37d33d80-e023-11eb-9299-0d9f3f1cabb4.png)
Left side is created in0.4.0. Right side is created in 0.3.1 (or older, can't remember)

**Comment by filips123** [comment]
You can try going into Firefox customize page and resetting widget layout to default.

I think that is because previously I just deleted new tab widget and now I'm hiding it (when not in tabs mode), so profile remembered that it shouldn't be displayed.

**Comment by pc-v2** [comment]
okay i will close this issue :)
