### ISSUE TITLE
Implement Open In PWA Is Not Working [Bug?]

### ISSUE THREAD

**Issue by pc-v2** [filips123/FirefoxPWA#32]
![image](https://user-images.githubusercontent.com/58063311/125215792-93811d80-e2e6-11eb-8fb0-4bbc01190ff2.png)

**Comment by filips123** [comment]
Was YouTube installed using manifest option or not? Sites that are not installed with manifest currently cannot be displayed in this list.

Also, is YouTube listed in the main list of PWAs (in the main extension popup) and in the console list (`firefoxpwa profile list`)?

Unfortunately I won't have time to debug this until Friday, but please check [troubleshooting wiki page](https://github.com/filips123/FirefoxPWA/wiki/Troubleshooting) and provide logs of the program and extension.

**Comment by pc-v2** [comment]
> Also, is YouTube listed in the main list of PWAs (in the main extension popup)

Yes, I add it directly from [Install this site] button with custom profile
(Edit : using default profile doesn't work too)
![image](https://user-images.githubusercontent.com/58063311/125439422-e4021050-9973-4c36-8a0e-dc8819d76abe.png)
[firefoxpwa-stderr.log](https://github.com/filips123/FirefoxPWA/files/6808269/firefoxpwa-stderr.log)
[firefoxpwa.log](https://github.com/filips123/FirefoxPWA/files/6808270/firefoxpwa.log)

**Comment by filips123** [comment]
This should be fixed in 0.4.1.
