### ISSUE TITLE
Is there any way to provide command-line arguments to the version of Firefox being used by FirefoxPWA?

### ISSUE THREAD

**Issue by asolidtime** [filips123/FirefoxPWA#39]

**Comment by filips123** [comment]
Currently not (without editing [the source code](https://github.com/filips123/FirefoxPWA/blob/main/native/src/components/site.rs#L120-L124) and specifying arguments there). However, I could add a way to provide arguments, maybe using some environment variable and/or additional arguments to the `site launch` command.

**Comment by filips123** [comment]
You will be able to provide Firefox arguments in 1.0.0 which will be released soon. There will be a few ways to do this:

* To specify arguments when launching a specific PWA from the command line: `firefoxpwa site launch ID --normal-arguments -- --firefox-arguments`
* To specify arguments when launching a specific PWA from start/app menu shortcut: Edit the shortcut (details depend on your OS) to provide arguments in the same way as above.
* For all PWAs: Edit FirefoxPWA config file (`%APPDATA%\FirefoxPWA\config.json`/`$XDG_DATA_HOME/firefoxpwa/config.json`/$HOME/Library/Application Support/firefoxpwa/config.json`) and include `arguments` as JSON list of arguments. For example:

```json
{
  "sites": {...},
  "profiles": {...},
  "arguments": ["--jsconsole", "--allow-downgrade"]
}
```
