### ISSUE TITLE
Addon link at release page

### ISSUE THREAD

**Issue by black7375** [filips123/FirefoxPWA#4]
If the add-on link is always included in the release notes, users will not have to wander around looking for the link.

Other projects to refer: https://webcatalog.app/ ([sourcecode](https://github.com/filips123/FirefoxPWA/issues/4#issue-936223720))
The UI/UX is quite good, and there is a store.

---

This project looks pretty good.
I introduced your project here:
- https://www.reddit.com/r/firefox/comments/ocuy5r/attempts_to_support_pwa_in_firefox
- https://news.ycombinator.com/item?id=27720529

Thank you for doing what mozilla has to do instead.

**Comment by filips123** [comment]
I now added a link to the addon store in release notes.

I will check WebCatalog for some inspiration. However, I think PWA store is out of scope for this project, because users can already easily install PWAs using addon.
