### ISSUE TITLE
Use Post Install Script for the .deb Releases to Add Repository to /etc/apt/sources.list.d 

### ISSUE THREAD

**Issue by wolfiediscord** [filips123/FirefoxPWA#46]
### Problem Description

My main concern is security. Some users will not choose to update the FirefoxPWA.deb file with every new release. They might either forget or just not care.

### Proposed Solution
Add a post install script that adds the packagecloud.io repository to /etc/apt/sources.list.d and the key. This would make updating much easier for the end user. Major programs like Google Chrome and Opera include a post install script that adds their key and repository to /etc/apt/sources.list.d. 

### Additional Information

[Debian Maintainer Scripts](https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html)

I could probably figure out how to make a PR, but it wouldn't be very good code.

**Comment by filips123** [comment]
I thought about doing this, but I fear some Linux users might not want that DEB packages automatically add third-party repositories (I guess for privacy and security), so users should probably be able to prevent this. I'm not sure what's the best way to do this.

Anyways, I will re-order installation section so packagecloud.io is the first option in the installation instructions in the next extension version. Extension also (by default) checks for outdated native program so it should hopefully force users to update it.
