### ISSUE TITLE
Feature request: UI option to update FirefoxPWA's patched Firefox install

### ISSUE THREAD

**Issue by PeterCxy** [filips123/FirefoxPWA#47]
### Problem Description

Currently FirefoxPWA downloads a Firefox runtime during the first-time setup process. It is possible to update it by using the cli program to uninstall and re-download the runtime, but it would be nice if there's an option in the extension's UI to do this in one click.

### Proposed Solution

Add an option to the extension to facilitate upgrade of the runtime.

**Comment by filips123** [comment]
I added an option to reinstall/update Firefox in the extension settings in 1.1.0:

![settings](https://user-images.githubusercontent.com/16626308/132138284-f5b167b1-eb7a-4dd8-b129-12e2b2e78a2a.png)

![popup](https://user-images.githubusercontent.com/16626308/132138302-72a95fde-5403-4ea4-bede-1020733d418f.png)
