### ISSUE TITLE
The color of active PWA tabs should be made semi-transparent

### ISSUE THREAD

**Issue by PeterCxy** [filips123/FirefoxPWA#48]
### Description

At least on Linux, Firefox defaults to a non-transparent color for active tabs (by default this is extracted from the system theme). This may look okay with some apps but terrible with others. If possible, maybe we should override the color in userChrome with something semi-transparent or at least make it match the app theme color.

### Affected Websites

A common example of this issue is YouTube as a PWA.

![2021-08-18_19-30](https://user-images.githubusercontent.com/4532423/129891050-da98a668-b0bc-4dc9-9a05-dd2b3b5eb37c.png)

### Environment

* Operating system: Linux
* System architecture: x86_64
* Desktop environment: KDE
* FirefoxPWA extension version: 1.0.0
* FirefoxPWA native version: 1.0.0
* Firefox version: 91

**Comment by filips123** [comment]
I agree that it looks bad with some apps. I will probably try to make tabs transparent or use some shade of app theme color next week.

**Comment by filips123** [comment]
Sorry for delay, but I didn't have much time last week. I implemented transparent tabs and will probably publish them soon. Here is how they look on some popular websites:

**YouTube (theme color `#FF0000`):**
![youtube](https://user-images.githubusercontent.com/16626308/131717870-87d488e7-886b-485b-924d-a55c5b39b57a.png)

**Twitter (theme color `#ffffff`):**
![twitter](https://user-images.githubusercontent.com/16626308/131717963-e25b40a2-9cc0-4401-9263-d73da11e6088.png)


**Spotify (theme color `#121212`):**
![spotify](https://user-images.githubusercontent.com/16626308/131718016-ef70d23e-e648-42ca-93ec-a7b322f78574.png)
