### ISSUE TITLE
Accessing about:support from a PWA

### ISSUE THREAD

**Issue by sh1ft-github** [filips123/FirefoxPWA#5]
I just added a PWA but I am looking for a way to access about:config through it. Since there is not URL bar how can I access it? I know that you can access settings through the hamburger menu at the top but what about about:config?

Specifically I wanted to import my Firefox profile with all the custom modifications.

**Comment by filips123** [comment]
I haven't documented this yet, but you can press `F6` and enter any URL.

**Comment by filips123** [comment]
I added documentation about this feature [to the repository wiki](https://github.com/filips123/FirefoxPWA/wiki/App-browser-Features#navigating-to-arbitrary-urls).
