### ISSUE TITLE
Extention support in PWA's

### ISSUE THREAD

**Issue by IntoTheVoid-900** [filips123/FirefoxPWA#51]
### Problem Description

When loading up a web app, you can not use any of your extensions. I need this mostly for Ublock Origin and Bitwarden.

### Proposed Solution

It would be good if you could implement support for Firefox extensions to the PWA's like seen in ones made on Chromium based browsers.

**Comment by black7375** [comment]
You can just install it.

1. Hamburger Menu
2. Add-ons and themes

**Comment by IntoTheVoid-900** [comment]
Thank you, I didn't realize you had to install the extensions again.

**Comment by black7375** [comment]
It uses the new runtime without sharing a profile with regular firefox.
