### ISSUE TITLE
PWAs fail to launch after upgrading

### ISSUE THREAD

**Issue by jdelisle** [filips123/FirefoxPWA#55]
### Description

Launching installed PWAs after upgrading fails and returns an error.

### Steps to Reproduce

1. Install extension + native 1.0.0
2. Install YouTube PWA
3. Upgrade extension + native to 1.1.0
4. Launch YouTube PWA

### Additional Information

Finder returns the following error:
`The application “YouTube.app” can’t be opened.`

The problem seems to be that PWA loader files have the version hardcoded into the path of the `firefoxpwa` binary.

Loader file:
`$HOME/Applications/YouTube.app/Contents/MacOS/loader`

Binary path:
`/usr/local/Cellar/firefoxpwa/1.0.0/bin/firefoxpwa`

Modifying the binary path to use the symlink fixes the issue:
`/usr/local/bin/firefoxpwa`

### Environment

* Operating system: macOS
* System architecture: x86
* Installation method: Homebrew
* FirefoxPWA extension version: 1.1.0
* FirefoxPWA native version: 1.1.0
* Firefox version: 91.0.2

**Comment by filips123** [comment]
Version is indeed hardcoded into the path in several files, and it is set [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/firefoxpwa.rb#L22) using the Homebrew `bin` which *should* be always updated to the correct version. However, it seems I forgot that PWA loaders also include versioned path to binary which is not updated.

I think I can solve this if I change `bin` in the formula (and `share`) to `opt_bin` which I think will use unversioned path.

**Comment by filips123** [comment]
I have published update/rebuild to 1.1.0 in [my Homebrew tap](https://github.com/filips123/homebrew-firefoxpwa) which should fix this issue (but it required some manual work). Can you check if it works so I can create PR to official Homebrew tap?

1. Activate my tap: `brew tap filips123/firefoxpwa`
2. Install/update new FirefoxPWA from tap: `brew install filips123/firefoxpwa/firefoxpwa`
3. Edit/update all existing PWAs through extension or command-line program to apply the fix to PWAs. This is unfortunately unavoidable and will need to be done even when update in the official tap is released.
4. Check if PWA loader file contains versioned path or not (it should not).

**Comment by jdelisle** [comment]
I just tried it and I do get the correct path now: `/usr/local/opt/firefoxpwa/bin/firefoxpwa`.

Thank you for this quick answer and fix as well as for this great project!
