### ISSUE TITLE
Can't create new PWA

### ISSUE THREAD

**Issue by MauriceNorden** [filips123/FirefoxPWA#59]
Hello there,

Recently i stumbled across your extension,
Everything seemed find till it was time to make a PWA.
When doing that i get a error code
`Failed to install system integration: Failed to process and store site icons: Failed to create icon directory: Permission denied (os error 13)`

I'm using fedora 34
![image](https://user-images.githubusercontent.com/43381188/135768062-b4e92aff-f317-405a-936f-e2e6433707cb.png)
And the latest version of Firefox( 92.0.1 64 bit)

![image](https://user-images.githubusercontent.com/43381188/135768071-8c4898fe-a295-4c69-94fc-493ff5f68de2.png)
I've already tried to install the 32bit version of firefoxpwa-1.1.0-1 but without any success.

If there is more information you need regarding about my setup please let me know

**Comment by filips123** [comment]
It seems directories where app icons should be installed (`~/.local/share/icons/hicolor/` or `$XDG_DATA_HOME/icons/hicolor/`, and its subdirectories such as `scalable/apps/`, `48x48/apps/`, `128x128/apps/` etc.) are not writable by FirefoxPWA for some reason. Can you check permissions of that directories?

**Comment by MauriceNorden** [comment]
ahhh thank you, the folders where not present on my system.
but i've created them manualy and with a bit of chmod magic it works now.

thanks for the quick response
