### ISSUE TITLE
Logged out of PWAs after reopening 

### ISSUE THREAD

**Issue by Oudstand** [filips123/FirefoxPWA#74]
### Description

I logged into the PWA for Spotify and after restarting it, I was logged out of the website. This seems to happen with all websites.

### Steps to Reproduce

1. Install [Spotify](https://open.spotify.com/) as a PWA.
2. Open Spotify and log in
3. Close Spotify
4. Start Spotify 

You should need to log in again.

### Affected Websites

* https://open.spotify.com/

### Environment

* Operating system: Windows 10
* System architecture: 64 bit
* Installation method: MSI
* FirefoxPWA extension version: 1.2.1
* FirefoxPWA native version: 1.2.1
* Firefox version: 96.0a1

**Comment by filips123** [comment]
This does not happen for me on websites I tested (although I haven't tested Spotify) with a completely fresh profiles. Maybe you have set some settings that clear your browsing data on exit or used some (probably privacy-related) extensions that prevent websites from storing some data. Can you try to create a new Spotify instance in fresh FirefoxPWA profile and check if it works there?

**Comment by black7375** [comment]
Confirmed Spotify works

**Comment by Oudstand** [comment]
I've created a new profile and now everything works fine. I don't know why it didn't work before because I didn't adjust any settings before. But thanks four your help.

**Comment by pwall2222** [comment]
Uhm sorry for bumping a 3 year old issue, but I am having this *exact* same issue on my Linux (NixOS 24.05, firefoxpwa 2.21.1) machine. 
And I tried reinstalling (with a new profile) a bunch of times, changing the default URL, etc.
There was nothing I could do to get it not to logout on Spotify.

**Comment by filips123** [comment]
Can you please try to create a new profile in normal/main Firefox and check if it works there?

**Comment by pwall2222** [comment]
> Can you please try to create a new profile in normal/main Firefox and check if it works there?

It happens the same on a *new* profile but not on the one I already have.
My steps were:

- Create a new profile
- Do absolutely nothing with it
- Login into Spotify
- Close the profile (my main profile remains open all through out if that's relevant)
- Open the profile again
- I am no longer logged in Spotify

**Comment by pwall2222** [comment]
> Can you please try to create a new profile in normal/main Firefox and check if it works there?

Yeah from a brand new profile it also does this, in my main Firefox instance.
This has left me even more confused though.

**Comment by filips123** [comment]
So, it seems some default Firefox settings interfere with Spotify logins. Maybe try to disable tracking protection for Spotify before you log in.

**Comment by pwall2222** [comment]
> So, it seems some default Firefox settings interfere with Spotify logins. Maybe try to disable tracking protection for Spotify before you log in.

I disabled all the tracking, even enabled DRM, still same thing.

**Comment by filips123** [comment]
You should probably report this to [Bugzilla](https://bugzilla.mozilla.org/home) (and check if it has been already reported), as it doeant seem to be caused by PWAsForFirefox and I don't know why it happens.
