### ISSUE TITLE
Option to hide titlebar/toolbar in full screen mode

### ISSUE THREAD

**Issue by wzxu** [filips123/FirefoxPWA#85]
### Problem Description

When entered full screen mode, there is still a titlebar/toolbar with the favicon, title, and overflow button shown over the top.
Being able to hide it will result in the most immersive PWA experience.

### Proposed Solution

An option to always hide it, until we hover over the menubar, then show it.
Aka the behavior when you deselect "Always Show Toolbar in Full Screen" in Chrome.

**Comment by wzxu** [comment]
Mock-up:
![spotify](https://user-images.githubusercontent.com/5619348/142765218-981717cd-3f9e-41e9-bdce-42cda0b5e8cb.png)

**Comment by filips123** [comment]
This should be default behaviour of Firefox when using full screen mode (F11), so I'm not sure why it doesn't work for you. But you can try to enable `browser.fullscreen.autohide` in `about:config` (press F6, enter `about:config` and search for this preference) and make sure "Title Bar" is disabled in the Firefox customize page.

**Comment by wzxu** [comment]
> browser.fullscreen.autohide

Huh. This one works. Wonder why it's not exposed as a user-accessable option by Firefox... but anyway, guess I should close this. Thanks for the hint!
